// Code generated by simpleassets DO NOT EDIT.
package lib

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io/ioutil"
	"strings"
)

// Asset stores the file data.
type Asset struct {
	Name       string
	Compressed bool
	Data       string
}

// Stored assets by filename
var assets = map[string]Asset{}

// ReadAsset reads an asset from the store.
func ReadAsset(name string) ([]byte, error) {

	// Get asset from map and verify
	asset, ok := assets[name]
	if !ok {
		return nil, fmt.Errorf("asset does not exist: %s", name)
	}

	// Decode base64
	decoded, err := base64.StdEncoding.DecodeString(asset.Data)
	if err != nil {
		return nil, err
	}

	// Decompress if required
	if asset.Compressed {
		reader, err := gzip.NewReader(bytes.NewReader(decoded))
		if err != nil {
			return nil, err
		}
		return ioutil.ReadAll(reader)
	}
	return decoded, nil
}

// WriteAsset writes an asset to the store.
func WriteAsset(name string, data []byte) {
	encoded := base64.StdEncoding.EncodeToString([]byte(data))

	// Add to list of asset names if needed
	if _, ok := assets[name]; !ok {
		assetNames = append(assetNames, name)
	}

	// Store assset
	assets[name] = Asset{Name: name, Compressed: false, Data: encoded}
}

// List of asset names
var assetNames = []string{
	"index.js",
	"lib.js",
}

// ListAssetNames returns the list of asset names
func ListAssetNames() []string {
	return assetNames
}

func init() {
	assets["index.js"] = Asset{Name: "index.js", Compressed: true, Data: asset0000}
	assets["lib.js"] = Asset{Name: "lib.js", Compressed: true, Data: asset0001}
}

var asset0000 = strings.Join([]string{
	"H4sIAAAAAAAA/2yMMQ6CQBBF+z3Fd6slEKL1Su8NrBdZyJiBIeNKQ7i7GTsTm5nk/bznaF5FC3ZaHtpg",
	"yHanXA6MKjM8U98+Xz66LSm2xO+MzvZQRTeKIhgndDhHEK642K/rCrsDAM7FLHSwvkmHm1j6xO2qtJTw",
	"TVXxF/ZF0j8W/C0zS4O7KA8nb+IHAAD//wEAAP//ZNbbYsEAAAA=",
}, "")

var asset0001 = strings.Join([]string{
	"H4sIAAAAAAAA/4zMQQqCIRAG0LVzisGVnkE6jX6JEKOMIwTR3cO2JfzrB4/wHF2N70uytS7cJGuI/CL3",
	"gLFiDr7xhJTgN/mYyClsqXwx0Zt+joLjsenSUWGHosL+DR8AAAD//wEAAP//0xjTacoAAAA=",
}, "")
